subscription analysisWasCreated {
  analysisWasCreated {
    id
    image_path
    position_start
    position_end
    state
    report_id
    cable_id
    cable {
      id
      size
      diameter
    }
  }
}